---
- name: "Ajout du template docker-compose.yml"
  template:
    src: "docker-compose.yml.j2"
    dest: /home/{{ ansible_user }}/docker-compose.yml

- name: Ensure python3-venv is installed
  apt:
    name: python3-venv
    state: present

- name: Create a Python virtual environment
  command: python3 -m venv {{ venv_path }}
  args:
    creates: "{{ venv_path }}"

- name: Ensure build essentials are installed
  apt:
    name:
      - build-essential
      - libffi-dev
      - libssl-dev
      - python3-dev
      - python3-pip
      - gcc
      - make
    state: present

- name: Download Docker Compose binary
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: "Lancer le fichier docker-compose.yml"
  command: "/usr/local/bin/docker-compose -f /home/{{ ansible_user }}/docker-compose.yml up -d"
  become: true

- name: "Relancer le container odoo apres l'init de la db"
  shell: |
    sleep 15
    docker container restart {{ odoo_container }}
    exit 0
